#!/bin/bash 

update_docker_service(){
  dependency_to_add=$1
  echo "about to add the following dependency for docker service: $dependency_to_add"

  if cat $docker_service_file_path | grep -q "$dependency_to_add"
  then 
    echo "docker.service file already updated"
  else
    echo "sudo sed -i /After/s/$/ $dependency_to_add/ $docker_service_file_path"
    sudo sed -i "/After/s/$/ $dependency_to_add/" $docker_service_file_path
    if [ $? -eq 0 ]
    then
      echo "$dependency_to_add has been added successfully"
    else
      echo "Error occured while trying to add $dependency_to_add"
      exit 1
    fi
  fi
}

check_docker_service_file_exists(){
  if [ ! -f $docker_service_file_path ]
  then
    echo "No such file $docker_service_file_path!"
    exit 1
  fi
}

docker_service_file_path=/etc/systemd/system/multi-user.target.wants/docker.service
check_docker_service_file_exists
update_docker_service <some mount name>.mount
update_docker_service <some mount name 2>.mount
